/**
 * 流沙聚·拾光
 *
 * @fileoverview 首页标语配置文件
 * @author      流沙聚开发团队
 * @company     流沙聚工作室
 * @version     1.0.0
 * @since       2025-12-16
 * @copyright   Copyright (c) 2025 流沙聚工作室. All rights reserved.
 * @license     商业软件，保留所有权利
 * @contact     https://www.icks018.cn
 *
 * 本软件为商业软件，严禁复制、传播、反编译或用于其他任何用途
 * 仅授权合法用户在许可范围内使用
 */

/**
 * 首页标语数据
 * © 2025 流沙聚·拾光. All rights reserved. 流沙聚工作室 版权所有
 */
export const slogans = [
  { badge: '每周精选', title: '拾起时光的碎片', description: '这里没有喧嚣，只有极简的代码与唯美的设计。\n收录互联网角落里，那些安静治愈的静态页面。' },
  { badge: '创意灵感', title: '发现美的瞬间', description: '每一个页面都是一件艺术品。\n在这里，遇见那些让人心动的设计。' },
  { badge: '精心收藏', title: '珍藏网络之美', description: '从千万页面中精选而出。\n只为呈现最纯粹的视觉体验。' },
  { badge: '治愈系', title: '静谧的数字花园', description: '远离喧嚣，回归简单。\n在这片净土中，感受代码的诗意。' },
  { badge: '设计美学', title: '极简主义之美', description: '少即是多，简约而不简单。\n探索设计的无限可能。' },
  { badge: '艺术收藏', title: '像素中的诗意', description: '每一行代码都是一首诗。\n每一个设计都是一幅画。' },
  { badge: '视觉盛宴', title: '色彩的交响曲', description: '在光影变幻中寻找灵感。\n让美好在屏幕上绽放。' },
  { badge: '简约风格', title: '留白的艺术', description: '空间即是设计的一部分。\n简洁中蕴含无限可能。' },
  { badge: '复古情怀', title: '时光的印记', description: '怀旧的设计，永恒的美感。\n在复古中找到新的灵感。' },
  { badge: '未来主义', title: '科技的温度', description: '冰冷的代码，温暖的设计。\n探索未来的无限可能。' },
  { badge: '自然之美', title: '有机的设计', description: '从自然中汲取灵感。\n让设计回归本真。' },
  { badge: '手工质感', title: '匠心独运', description: '每一个细节都值得推敲。\n用心雕琢每一个像素。' },
  { badge: '动态美学', title: '流动的艺术', description: '在动与静之间找到平衡。\n让页面充满生命力。' },
  { badge: '几何图形', title: '线条的魔法', description: '简单的形状，无限的组合。\n几何之美，尽在其中。' },
  { badge: '色彩理论', title: '调色板的秘密', description: '每一种颜色都有故事。\n在色彩中找到情感。' },
  { badge: '排版艺术', title: '文字的舞蹈', description: '字体即是设计的灵魂。\n让文字在页面上起舞。' },
  { badge: '交互设计', title: '触摸的温度', description: '每一次点击都是对话。\n让交互成为艺术。' },
  { badge: '响应式', title: '自适应的美', description: '在任何屏幕上都完美呈现。\n设计无处不在。' },
  { badge: '微交互', title: '细节的力量', description: '小小的动画，大大的惊喜。\n细节决定成败。' },
  { badge: '品牌设计', title: '视觉的语言', description: '用设计讲述品牌故事。\n让视觉成为记忆。' },
  { badge: '插画风格', title: '手绘的温暖', description: '每一笔都是情感的流露。\n插画让设计更有温度。' },
  { badge: '摄影美学', title: '光影的诗篇', description: '用镜头捕捉瞬间。\n让照片诉说故事。' },
  { badge: '3D视觉', title: '立体的世界', description: '突破平面的限制。\n在三维空间中探索。' },
  { badge: '扁平设计', title: '纯粹的表达', description: '去除多余的装饰。\n回归设计的本质。' },
  { badge: '拟物风格', title: '真实的触感', description: '让数字世界更真实。\n拟物设计的魅力。' },
  { badge: '玻璃拟态', title: '透明的美学', description: '模糊与清晰之间。\n玻璃质感的优雅。' },
  { badge: '新拟态', title: '柔和的阴影', description: '光影塑造形态。\n新拟态的温柔。' },
  { badge: '暗黑模式', title: '夜的温柔', description: '在黑暗中寻找光明。\n暗黑也可以很美。' },
  { badge: '渐变色彩', title: '色彩的流动', description: '从一种颜色到另一种。\n渐变中的无限可能。' },
  { badge: '极光效果', title: '梦幻的光影', description: '如极光般绚丽。\n让页面充满魔力。' },
  { badge: '毛玻璃', title: '朦胧的美感', description: '透过玻璃看世界。\n模糊中的清晰。' },
  { badge: '粒子特效', title: '星尘的轨迹', description: '无数粒子组成画面。\n动态之美尽显。' },
  { badge: '波浪效果', title: '流体的韵律', description: '如水波般流动。\n让设计更有动感。' },
  { badge: '视差滚动', title: '层次的魔法', description: '不同的速度，不同的层次。\n视差带来深度。' },
  { badge: '全屏设计', title: '沉浸的体验', description: '让内容占据整个视野。\n沉浸式的享受。' },
  { badge: '卡片布局', title: '模块的美学', description: '每一张卡片都是故事。\n模块化的优雅。' },
  { badge: '网格系统', title: '秩序的力量', description: '在网格中找到平衡。\n秩序即是美。' },
  { badge: '不对称', title: '打破的平衡', description: '不对称中的和谐。\n突破传统的束缚。' },
  { badge: '黄金比例', title: '完美的比例', description: '自然界的黄金法则。\n比例决定美感。' },
  { badge: '留白空间', title: '呼吸的艺术', description: '给设计留出呼吸的空间。\n留白即是设计。' },
  { badge: '对比强烈', title: '冲突的美学', description: '在对比中找到张力。\n强烈即是印象。' },
  { badge: '和谐统一', title: '协调的力量', description: '所有元素和谐共存。\n统一中的多样。' },
  { badge: '节奏韵律', title: '视觉的音乐', description: '设计也有节奏感。\n韵律带来美感。' },
  { badge: '重复元素', title: '一致的语言', description: '重复创造统一感。\n一致性的力量。' },
  { badge: '焦点突出', title: '视线的引导', description: '让重要的更重要。\n焦点即是核心。' },
  { badge: '层次分明', title: '信息的架构', description: '清晰的层次结构。\n让信息易于理解。' },
  { badge: '情感设计', title: '触动的心灵', description: '设计不只是视觉。\n更是情感的传递。' },
  { badge: '故事叙述', title: '设计的叙事', description: '每个设计都在讲故事。\n让故事打动人心。' },
  { badge: '用户体验', title: '以人为本', description: '设计为用户服务。\n体验即是一切。' },
  { badge: '可访问性', title: '包容的设计', description: '让每个人都能使用。\n设计应该包容。' },
  { badge: '性能优化', title: '速度的美学', description: '快速即是体验。\n性能也是设计。' },
  { badge: '移动优先', title: '指尖的艺术', description: '为移动设备而生。\n触摸即是交互。' },
  { badge: '跨平台', title: '无处不在', description: '在任何设备上都完美。\n设计无边界。' },
  { badge: '渐进增强', title: '层层递进', description: '基础功能到高级体验。\n渐进式的优雅。' },
  { badge: '优雅降级', title: '兼容的智慧', description: '在任何环境都能工作。\n降级也要优雅。' },
  { badge: '模块化', title: '组件的哲学', description: '可复用的设计单元。\n模块化的力量。' },
  { badge: '原子设计', title: '从小到大', description: '从原子到页面。\n系统化的思维。' },
  { badge: '设计系统', title: '统一的语言', description: '建立设计的规范。\n系统带来一致。' },
  { badge: '品牌一致', title: '识别的力量', description: '保持品牌的统一性。\n一致即是记忆。' },
  { badge: '创新突破', title: '打破的常规', description: '不拘泥于传统。\n创新带来惊喜。' },
  { badge: '实验精神', title: '探索的勇气', description: '勇于尝试新事物。\n实验即是进步。' },
  { badge: '趋势把握', title: '时代的脉搏', description: '紧跟设计潮流。\n趋势引领未来。' },
  { badge: '经典永恒', title: '不朽的设计', description: '经典永不过时。\n永恒的美学。' },
  { badge: '文化融合', title: '东西方的对话', description: '融合不同文化元素。\n碰撞出新火花。' },
  { badge: '本土特色', title: '地域的印记', description: '展现本土文化。\n特色即是优势。' },
  { badge: '国际视野', title: '全球的眼光', description: '放眼世界设计。\n视野决定高度。' },
  { badge: '环保理念', title: '绿色的设计', description: '可持续的设计思维。\n环保即是责任。' },
  { badge: '社会责任', title: '设计的担当', description: '设计改变世界。\n责任重于泰山。' },
  { badge: '人文关怀', title: '温暖的科技', description: '科技应该有温度。\n关怀即是设计。' },
  { badge: '无障碍', title: '平等的权利', description: '让所有人都能访问。\n无障碍即是尊重。' },
  { badge: '隐私保护', title: '安全的设计', description: '保护用户隐私。\n安全即是信任。' },
  { badge: '数据可视', title: '信息的艺术', description: '让数据变得美丽。\n可视化的力量。' },
  { badge: '信息架构', title: '结构的智慧', description: '清晰的信息组织。\n架构决定体验。' },
  { badge: '内容为王', title: '本质的回归', description: '内容才是核心。\n设计服务内容。' },
  { badge: '视觉层次', title: '引导的艺术', description: '用层次引导视线。\n层次即是逻辑。' },
  { badge: '空间感', title: '深度的营造', description: '在平面创造深度。\n空间即是维度。' },
  { badge: '质感表现', title: '材质的语言', description: '不同材质不同感受。\n质感即是细节。' },
  { badge: '光影效果', title: '明暗的对话', description: '光影塑造形态。\n明暗即是立体。' },
  { badge: '动效设计', title: '运动的美学', description: '让静态变为动态。\n动效即是生命。' },
  { badge: '转场过渡', title: '流畅的衔接', description: '自然的页面切换。\n过渡即是连贯。' },
  { badge: '加载动画', title: '等待的艺术', description: '让等待不再枯燥。\n加载也是体验。' },
  { badge: '反馈机制', title: '对话的设计', description: '及时的用户反馈。\n反馈即是沟通。' },
  { badge: '错误处理', title: '友好的提示', description: '优雅地处理错误。\n错误也要美观。' },
  { badge: '引导流程', title: '顺畅的旅程', description: '引导用户完成任务。\n流程即是体验。' },
  { badge: '个性化', title: '独特的体验', description: '为每个用户定制。\n个性即是关怀。' },
  { badge: '智能推荐', title: '懂你的设计', description: '智能理解用户需求。\n推荐即是服务。' },
  { badge: '情境感知', title: '场景的适应', description: '根据场景调整设计。\n情境即是智能。' },
  { badge: '多语言', title: '全球的沟通', description: '跨越语言的障碍。\n多语言即是包容。' },
  { badge: '文化适配', title: '本地化的智慧', description: '尊重不同文化。\n适配即是尊重。' },
  { badge: '时区处理', title: '时间的艺术', description: '适应全球时区。\n时间即是体验。' },
  { badge: '货币格式', title: '细节的考量', description: '正确显示货币。\n格式即是专业。' },
  { badge: '单位转换', title: '度量的统一', description: '适应不同度量单位。\n转换即是便利。' },
  { badge: '搜索优化', title: '发现的便捷', description: '让用户快速找到。\n搜索即是效率。' },
  { badge: '导航设计', title: '路径的清晰', description: '清晰的导航结构。\n导航即是地图。' },
  { badge: '面包屑', title: '位置的标记', description: '让用户知道在哪。\n面包屑即是指引。' },
  { badge: '页脚设计', title: '收尾的艺术', description: '完美的页面结束。\n页脚也重要。' },
  { badge: '404页面', title: '迷失的温暖', description: '友好的错误页面。\n404也要美。' },
  { badge: '空状态', title: '留白的智慧', description: '优雅地处理空内容。\n空也是一种美。' },
  { badge: '诗意代码', title: '字节间的浪漫', description: '每一行代码都是情书。\n在0与1之间书写诗篇。' },
  { badge: '月光设计', title: '银色的梦境', description: '如月光般温柔的设计。\n在夜色中绽放光芒。' },
  { badge: '晨曦之美', title: '黎明的色彩', description: '捕捉清晨的第一缕阳光。\n让设计充满希望。' },
  { badge: '星空漫步', title: '宇宙的诗篇', description: '在星辰大海中遨游。\n探索无限的可能。' },
  { badge: '樱花飘落', title: '瞬间的永恒', description: '如樱花般短暂而美丽。\n定格最美的瞬间。' },
  { badge: '秋叶静美', title: '时光的沉淀', description: '金黄的叶片诉说故事。\n在变化中寻找永恒。' },
  { badge: '雪落无声', title: '纯净的世界', description: '如雪花般纯粹的设计。\n在寂静中感受美好。' },
  { badge: '春风拂面', title: '温柔的触碰', description: '如春风般轻柔的交互。\n让设计充满生机。' },
  { badge: '夏日蝉鸣', title: '热烈的生命', description: '如蝉鸣般热烈的色彩。\n在炎夏中绽放活力。' },
  { badge: '雨后彩虹', title: '希望的色彩', description: '风雨过后见彩虹。\n在困难中看到美好。' },
  { badge: '晚霞余晖', title: '温暖的告别', description: '如晚霞般绚烂的结尾。\n完美地画上句号。' },
  { badge: '流星划过', title: '瞬间的璀璨', description: '如流星般短暂而耀眼。\n把握每一个瞬间。' },
  { badge: '云卷云舒', title: '自在的变化', description: '如云朵般自由变幻。\n在流动中找到美感。' },
  { badge: '海浪轻拍', title: '节奏的韵律', description: '如海浪般有节奏的设计。\n在重复中创造美感。' },
  { badge: '山峦叠翠', title: '层次的美学', description: '如山峦般层层叠叠。\n在深度中展现魅力。' },
  { badge: '溪水潺潺', title: '流动的音符', description: '如溪水般清澈流畅。\n让设计自然流动。' },
  { badge: '竹林幽径', title: '静谧的空间', description: '如竹林般清幽雅致。\n在宁静中感受禅意。' },
  { badge: '荷塘月色', title: '诗意的夜晚', description: '如荷塘般清新脱俗。\n在月色中品味优雅。' },
  { badge: '梅花傲雪', title: '坚韧的美丽', description: '如梅花般傲然绽放。\n在寒冬中展现风骨。' },
  { badge: '兰花幽香', title: '淡雅的气质', description: '如兰花般清雅脱俗。\n在简约中显高贵。' },
  { badge: '菊花秋韵', title: '从容的姿态', description: '如菊花般淡定从容。\n在秋日中展现风采。' },
  { badge: '牡丹雍容', title: '华贵的气度', description: '如牡丹般雍容华贵。\n在绽放中显尊贵。' },
  { badge: '蝴蝶翩跹', title: '轻盈的舞蹈', description: '如蝴蝶般轻盈优雅。\n在飞舞中展现美态。' },
  { badge: '蜻蜓点水', title: '灵动的瞬间', description: '如蜻蜓般轻巧灵动。\n在点触中创造涟漪。' },
  { badge: '鱼跃龙门', title: '跨越的勇气', description: '如鱼跃般勇往直前。\n在突破中实现梦想。' },
  { badge: '鹤舞云端', title: '优雅的姿态', description: '如仙鹤般优雅高贵。\n在云端中自由翱翔。' },
  { badge: '凤凰涅槃', title: '重生的力量', description: '如凤凰般浴火重生。\n在蜕变中获得新生。' },
  { badge: '龙腾四海', title: '磅礴的气势', description: '如神龙般气势磅礴。\n在翱翔中展现威严。' },
  { badge: '琴瑟和鸣', title: '和谐的乐章', description: '如琴瑟般和谐共鸣。\n在协奏中创造美妙。' },
  { badge: '书香墨韵', title: '文化的底蕴', description: '如书香般悠远绵长。\n在文字中品味韵味。' },
  { badge: '茶道禅心', title: '静心的修行', description: '如茶道般静心凝神。\n在品茗中感悟人生。' },
  { badge: '花道美学', title: '插花的艺术', description: '如花道般精致优雅。\n在插花中领悟美学。' },
  { badge: '香道雅韵', title: '芬芳的记忆', description: '如香道般馥郁芬芳。\n在香气中唤起回忆。' },
  { badge: '剑道精神', title: '专注的力量', description: '如剑道般专注凝练。\n在修行中追求极致。' },
  { badge: '水墨丹青', title: '写意的境界', description: '如水墨般意境深远。\n在留白中展现韵味。' },
  { badge: '工笔细描', title: '精细的刻画', description: '如工笔般细腻入微。\n在细节中展现功力。' },
  { badge: '泼墨山水', title: '豪放的气魄', description: '如泼墨般酣畅淋漓。\n在挥洒中展现气势。' },
  { badge: '青花瓷韵', title: '古典的优雅', description: '如青花瓷般清雅脱俗。\n在蓝白中品味经典。' },
  { badge: '玉石温润', title: '内敛的光泽', description: '如美玉般温润内敛。\n在含蓄中展现品质。' },
  { badge: '丝绸柔滑', title: '细腻的质感', description: '如丝绸般柔滑细腻。\n在触感中传递温柔。' },
  { badge: '陶瓷釉色', title: '窑变的惊喜', description: '如陶瓷般变幻莫测。\n在烧制中创造奇迹。' },
  { badge: '漆器光泽', title: '时光的沉淀', description: '如漆器般光泽内敛。\n在岁月中愈发醇厚。' },
  { badge: '竹编纹理', title: '编织的智慧', description: '如竹编般精巧细致。\n在交织中展现技艺。' },
  { badge: '木雕纹路', title: '刀工的艺术', description: '如木雕般纹理清晰。\n在雕刻中展现匠心。' },
  { badge: '石刻印记', title: '永恒的记录', description: '如石刻般历久弥新。\n在镌刻中留下印记。' },
  { badge: '剪纸镂空', title: '虚实的对话', description: '如剪纸般虚实相生。\n在镂空中展现灵动。' },
  { badge: '刺绣针法', title: '穿针引线', description: '如刺绣般精细入微。\n在针线中绣出美好。' },
  { badge: '织锦图案', title: '经纬交织', description: '如织锦般华美绚丽。\n在交织中展现繁复。' },
  { badge: '扎染晕染', title: '自然的纹理', description: '如扎染般自然随性。\n在晕染中创造惊喜。' },
  { badge: '蜡染图腾', title: '民族的印记', description: '如蜡染般古朴神秘。\n在图腾中传承文化。' },
  { badge: '皮影戏韵', title: '光影的魔术', description: '如皮影般虚实交错。\n在光影中演绎故事。' },
  { badge: '木偶戏趣', title: '提线的艺术', description: '如木偶般灵动有趣。\n在操控中展现技巧。' },
  { badge: '京剧脸谱', title: '色彩的符号', description: '如脸谱般色彩鲜明。\n在图案中表达性格。' },
  { badge: '昆曲婉转', title: '曲调的优雅', description: '如昆曲般婉转悠扬。\n在唱腔中品味雅韵。' },
  { badge: '古琴清音', title: '弦上的诗意', description: '如古琴般清雅悠远。\n在琴音中感受禅意。' },
  { badge: '箫声悠扬', title: '竹管的清音', description: '如洞箫般悠扬清远。\n在箫声中寻找宁静。' },
  { badge: '琵琶弹拨', title: '指尖的韵律', description: '如琵琶般铿锵有力。\n在弹拨中展现激情。' },
  { badge: '二胡拉奏', title: '弓弦的对话', description: '如二胡般婉转动人。\n在拉奏中诉说情感。' },
  { badge: '古筝流水', title: '指法的灵动', description: '如古筝般清脆悦耳。\n在拨弦中流淌音符。' },
  { badge: '笛声清脆', title: '竹笛的灵韵', description: '如竹笛般清脆嘹亮。\n在笛声中展现活力。' },
  { badge: '鼓点节奏', title: '击打的力量', description: '如鼓点般铿锵有力。\n在节奏中传递能量。' },
  { badge: '钟声悠远', title: '回响的余韵', description: '如钟声般悠远绵长。\n在回响中感受庄严。' },
  { badge: '风铃清脆', title: '微风的歌唱', description: '如风铃般清脆悦耳。\n在摇曳中奏响乐章。' },
  { badge: '流水潺潺', title: '自然的音符', description: '如流水般清澈动听。\n在流淌中演奏乐曲。' },
  { badge: '鸟鸣啁啾', title: '清晨的问候', description: '如鸟鸣般清脆婉转。\n在啁啾中唤醒黎明。' },
  { badge: '蛙声阵阵', title: '夏夜的合唱', description: '如蛙声般此起彼伏。\n在合唱中奏响夏日。' },
  { badge: '虫鸣唧唧', title: '秋夜的低语', description: '如虫鸣般轻声细语。\n在唧唧中诉说秋意。' },
  { badge: '松涛阵阵', title: '风过的声音', description: '如松涛般雄浑有力。\n在涛声中感受自然。' },
  { badge: '竹叶沙沙', title: '风吹的韵律', description: '如竹叶般沙沙作响。\n在摇曳中展现灵动。' },
  { badge: '雨打芭蕉', title: '雨滴的节奏', description: '如雨打芭蕉般清脆。\n在雨声中品味诗意。' },
  { badge: '雪落无声', title: '寂静的美丽', description: '如雪落般静谧无声。\n在寂静中感受纯净。' },
  { badge: '冰裂纹路', title: '自然的纹理', description: '如冰裂般自然随性。\n在纹路中展现美感。' },
  { badge: '霜花晶莹', title: '冬日的礼物', description: '如霜花般晶莹剔透。\n在晶莹中展现精致。' },
  { badge: '露珠晶莹', title: '清晨的珍珠', description: '如露珠般晶莹透亮。\n在晶莹中折射光芒。' },
  { badge: '雾气朦胧', title: '朦胧的美感', description: '如雾气般朦胧梦幻。\n在朦胧中展现神秘。' },
  { badge: '云海翻腾', title: '壮阔的景象', description: '如云海般波澜壮阔。\n在翻腾中展现气势。' },
  { badge: '日出东方', title: '希望的开始', description: '如日出般充满希望。\n在升起中迎接新生。' },
  { badge: '月升中天', title: '宁静的时刻', description: '如月升般宁静祥和。\n在月光中感受安详。' },
  { badge: '星河璀璨', title: '梦幻的夜空', description: '如星河般璀璨夺目。\n在星光中编织梦想。' },
  { badge: '极光绚烂', title: '天空的舞蹈', description: '如极光般绚丽多彩。\n在舞动中展现奇迹。' },
  { badge: '彩虹桥梁', title: '连接的纽带', description: '如彩虹般架起桥梁。\n在色彩中传递希望。' },
  { badge: '闪电划破', title: '瞬间的力量', description: '如闪电般震撼人心。\n在划破中展现威力。' },
  { badge: '雷声滚滚', title: '天空的鼓点', description: '如雷声般震撼心灵。\n在滚滚中传递力量。' },
  { badge: '彩霞满天', title: '天空的画布', description: '如彩霞般绚丽多姿。\n在满天中展现美景。' },
  { badge: '晨曦微露', title: '黎明的曙光', description: '如晨曦般温柔明亮。\n在微露中迎接新日。' },
  { badge: '暮色苍茫', title: '黄昏的诗意', description: '如暮色般苍茫深远。\n在苍茫中品味沧桑。' },
  { badge: '夜幕降临', title: '夜的序曲', description: '如夜幕般徐徐降临。\n在降临中开启夜晚。' },
  { badge: '星光点点', title: '夜空的钻石', description: '如星光般点点闪烁。\n在闪烁中装点夜空。' },
  { badge: '月光如水', title: '银色的诗篇', description: '如月光般清澈如水。\n在流淌中洒满大地。' },
  { badge: '萤火微光', title: '夏夜的精灵', description: '如萤火般微弱闪烁。\n在微光中点亮黑暗。' },
  { badge: '烛光摇曳', title: '温暖的光芒', description: '如烛光般温暖柔和。\n在摇曳中传递温情。' },
  { badge: '灯火阑珊', title: '繁华的尽头', description: '如灯火阑珊般静谧。\n在尽头中寻找自我。' },
  { badge: '霓虹闪烁', title: '都市的夜晚', description: '如霓虹般绚丽多彩。\n在闪烁中展现繁华。' },
  { badge: '烟火绽放', title: '瞬间的绚烂', description: '如烟火般璀璨夺目。\n在绽放中展现美丽。' },
];
